config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :animals

  root 'animals#index'

end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end

  def new
  end

  def create
    @animal = Animal.new(params.require(:animal).permit(:name, :color, :sex, :breed))

    @animal.save
    redirect_to @animal
  end

  def show
    @animal = Animal.find(params[:id])
  end

  private
    def animals_params
      params.require(:animal).permit(:name, :color, :sex, :breed)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animals/index.html.erb
<h1>Fantastic Beasts Shelter</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @animals.each do |animal| %>
    <tr>
      <td><%= animal.name %></td>
      <td><%= animal.sex %></td>
      <td><%= animal.breed %></td>
      <td><%= animal.color %></td>
      <td><%= animal.likes %></td>
      <td><%= link_to 'Show', animals_path(animal) %></td>
    </tr>
  <% end %>
</table>

app/views/animals/new.html.erb
<h1>List of Animals</h1>

<%= form_with scope: :animal, url: animals_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/animals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasticBeastsShelter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<%= link_to 'Animals', controller: 'animals' %>